import Head from 'next/head'
import Image from 'next/image'
import Slider from 'react-slick'
import Carousel from '../components/Carousel'
import ImagesContainer from '../components/ImagesContainer'


export default function Home() {

  const pics = Array(15).fill(0).map((i,index)=>index+1000+11)

  const sliderimage = ['/1.webp','/2.webp','/3.webp','/4.jpg','/5.jpg','/6.webp']
  const deals = ['/1011.webp','/1012.webp','/1013.webp','/1014.webp','/1015.jpg']
  const bigdeals = ['/1016.webp','/1017.webp','/1018.webp','/1019.webp','/1020.webp','/1021.webp','/1022.webp','/1023.webp','/1024.webp','/1025.webp']
  const footwear = ['/1076.webp','/1077.webp','/1078.webp','/1079.webp','/1080.jpg']
  const category1 = ['/1026.webp','/1027.webp','/1028.webp','/1029.webp','/1030.webp']
  const category2 = ['/1031.webp','/1032.webp','/1033.webp','/1034.webp','/1035.webp']




  

  return (
    <div  className='max-w-[1500px] mx-auto flex flex-col w-screen'>
      <Head>
        <title>Myntra-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex flex-col '>


        <Carousel sliderimage={sliderimage}/>
        <ImagesContainer lists={deals} title={'Deals of the day'}/>
        <ImagesContainer lists={bigdeals} title={'biggest deals on top brands'}/>
        <div className='flex flex-col -space-y-60'>

        <ImagesContainer lists={category1} title={'categories'}/>
        <div className='hidden lg:block'>

        <ImagesContainer lists={category2} title={'categories'} />
        </div>
        </div>
        <ImagesContainer lists={footwear} title={'Footwear'} />




   

        
        


        
      </main>

     
    </div>
  )
}
